### ISSUE TITLE
Deleting Creates New Text

### ISSUE THREAD

**Issue by Can1Cyp2** [jordanlandry/janninscript-online#1]
![buildjannin](https://user-images.githubusercontent.com/93102902/216234043-7762b9d1-bd03-464e-a5cf-697f9b64b5c2.PNG)

When using the arrows to go left and remove a letter in the print text, it adds a bracket to the left of the text.

**Comment by jordanlandry** [comment]
Issue is fixed now... weirdly enough I wasn't able to recreate this issue on 3 different systems using 4 different web browsers, but the issue was duplicate keys... It is fixed now
